### ISSUE TITLE
Errors with latest node.js release

### ISSUE THREAD

**Issue by raid5** [mikeal/tweetstream#3]
I get the following error when trying to use this module:

`options.bodyStream and options.responseBodyStream is deprecated. You should now send the request object to stream.pipe()`

**Comment by mikeal** [comment]
You have a newer version of request.

There are some bugs in the new API so I'm not going to update tweetstream yet.

For now you can just ignore these warnings.

**Comment by raid5** [comment]
Okay, I figured it had something to do with the latest version of node. When ignoring this warnings, no tweets are returned via the streaming api, so there is apparently more things broken.

**Comment by mikeal** [comment]
i'm tracking down a few bugs in streaming right now. i'll get to this one as soon as I can, currently hunting down some bugs in https clients.

**Comment by raid5** [comment]
hey, no worries. just keep me updated :)
